class Sensors:
    def __init__(self):
        pass

    DISTANCE_FRONT_FRONT = "DISTANCE_FRONT_FRONT"
    DISTANCE_FRONT_LEFT = "DISTANCE_FRONT_LEFT"
    DISTANCE_FRONT_RIGHT = "DISTANCE_FRONT_RIGHT"
